[package]
name = "graphgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

code_indexing = { path = "../code_indexing", version = "0.1.0" }

